// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: image_to_audio.proto

package image_to_audio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequestWithMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	SomeFloat     float64                `protobuf:"fixed64,2,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`  // Example float64
	SomeInt       int32                  `protobuf:"varint,3,opt,name=some_int,json=someInt,proto3" json:"some_int,omitempty"`         // Example int
	SomeString    string                 `protobuf:"bytes,4,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"` // Example string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequestWithMetadata) Reset() {
	*x = ImageRequestWithMetadata{}
	mi := &file_image_to_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequestWithMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequestWithMetadata) ProtoMessage() {}

func (x *ImageRequestWithMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_image_to_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequestWithMetadata.ProtoReflect.Descriptor instead.
func (*ImageRequestWithMetadata) Descriptor() ([]byte, []int) {
	return file_image_to_audio_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequestWithMetadata) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageRequestWithMetadata) GetSomeFloat() float64 {
	if x != nil {
		return x.SomeFloat
	}
	return 0
}

func (x *ImageRequestWithMetadata) GetSomeInt() int32 {
	if x != nil {
		return x.SomeInt
	}
	return 0
}

func (x *ImageRequestWithMetadata) GetSomeString() string {
	if x != nil {
		return x.SomeString
	}
	return ""
}

type SoundRequestWithMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoundData     []byte                 `protobuf:"bytes,1,opt,name=sound_data,json=soundData,proto3" json:"sound_data,omitempty"`
	AnotherFloat  float64                `protobuf:"fixed64,2,opt,name=another_float,json=anotherFloat,proto3" json:"another_float,omitempty"`  // Example float64
	AnotherInt    int32                  `protobuf:"varint,3,opt,name=another_int,json=anotherInt,proto3" json:"another_int,omitempty"`         // Example int
	AnotherString string                 `protobuf:"bytes,4,opt,name=another_string,json=anotherString,proto3" json:"another_string,omitempty"` // Example string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoundRequestWithMetadata) Reset() {
	*x = SoundRequestWithMetadata{}
	mi := &file_image_to_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoundRequestWithMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundRequestWithMetadata) ProtoMessage() {}

func (x *SoundRequestWithMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_image_to_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundRequestWithMetadata.ProtoReflect.Descriptor instead.
func (*SoundRequestWithMetadata) Descriptor() ([]byte, []int) {
	return file_image_to_audio_proto_rawDescGZIP(), []int{1}
}

func (x *SoundRequestWithMetadata) GetSoundData() []byte {
	if x != nil {
		return x.SoundData
	}
	return nil
}

func (x *SoundRequestWithMetadata) GetAnotherFloat() float64 {
	if x != nil {
		return x.AnotherFloat
	}
	return 0
}

func (x *SoundRequestWithMetadata) GetAnotherInt() int32 {
	if x != nil {
		return x.AnotherInt
	}
	return 0
}

func (x *SoundRequestWithMetadata) GetAnotherString() string {
	if x != nil {
		return x.AnotherString
	}
	return ""
}

type SoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoundData     []byte                 `protobuf:"bytes,1,opt,name=sound_data,json=soundData,proto3" json:"sound_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoundResponse) Reset() {
	*x = SoundResponse{}
	mi := &file_image_to_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundResponse) ProtoMessage() {}

func (x *SoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_to_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundResponse.ProtoReflect.Descriptor instead.
func (*SoundResponse) Descriptor() ([]byte, []int) {
	return file_image_to_audio_proto_rawDescGZIP(), []int{2}
}

func (x *SoundResponse) GetSoundData() []byte {
	if x != nil {
		return x.SoundData
	}
	return nil
}

type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_image_to_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_to_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_image_to_audio_proto_rawDescGZIP(), []int{3}
}

func (x *ImageResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

var File_image_to_audio_proto protoreflect.FileDescriptor

var file_image_to_audio_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f,
	0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x18, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0xa6, 0x01,
	0x0a, 0x18, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f,
	0x75, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x6f, 0x75, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6e, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0c, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x6f, 0x75,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x32, 0xc5, 0x01, 0x0a, 0x13, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x6f, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56,
	0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x28, 0x2e,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1d, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x28, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f,
	0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x1d, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_to_audio_proto_rawDescOnce sync.Once
	file_image_to_audio_proto_rawDescData = file_image_to_audio_proto_rawDesc
)

func file_image_to_audio_proto_rawDescGZIP() []byte {
	file_image_to_audio_proto_rawDescOnce.Do(func() {
		file_image_to_audio_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_to_audio_proto_rawDescData)
	})
	return file_image_to_audio_proto_rawDescData
}

var file_image_to_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_image_to_audio_proto_goTypes = []any{
	(*ImageRequestWithMetadata)(nil), // 0: image_to_audio.ImageRequestWithMetadata
	(*SoundRequestWithMetadata)(nil), // 1: image_to_audio.SoundRequestWithMetadata
	(*SoundResponse)(nil),            // 2: image_to_audio.SoundResponse
	(*ImageResponse)(nil),            // 3: image_to_audio.ImageResponse
}
var file_image_to_audio_proto_depIdxs = []int32{
	0, // 0: image_to_audio.ImageToSoundService.UploadImage:input_type -> image_to_audio.ImageRequestWithMetadata
	1, // 1: image_to_audio.ImageToSoundService.UploadSound:input_type -> image_to_audio.SoundRequestWithMetadata
	2, // 2: image_to_audio.ImageToSoundService.UploadImage:output_type -> image_to_audio.SoundResponse
	3, // 3: image_to_audio.ImageToSoundService.UploadSound:output_type -> image_to_audio.ImageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_to_audio_proto_init() }
func file_image_to_audio_proto_init() {
	if File_image_to_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_to_audio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_to_audio_proto_goTypes,
		DependencyIndexes: file_image_to_audio_proto_depIdxs,
		MessageInfos:      file_image_to_audio_proto_msgTypes,
	}.Build()
	File_image_to_audio_proto = out.File
	file_image_to_audio_proto_rawDesc = nil
	file_image_to_audio_proto_goTypes = nil
	file_image_to_audio_proto_depIdxs = nil
}
